import { join } from 'node:path'
import { writeFileSync, readFileSync, existsSync } from 'node:fs'
import type { ServerType } from '@shared/types'

export function writeEula(dir: string, accepted: boolean): void {
  writeFileSync(join(dir, 'eula.txt'), `eula=${accepted ? 'true' : 'false'}\n`, 'utf-8')
}

/** Merge/set keys in server.properties, creating the file if it doesn't exist. */
export function setServerProperties(dir: string, kv: Record<string, string | number>): void {
  const path = join(dir, 'server.properties')
  const map = new Map<string, string>()
  if (existsSync(path)) {
    for (const line of readFileSync(path, 'utf-8').split(/\r?\n/)) {
      if (!line || line.startsWith('#')) continue
      const eq = line.indexOf('=')
      if (eq > 0) map.set(line.slice(0, eq), line.slice(eq + 1))
    }
  }
  for (const [k, v] of Object.entries(kv)) map.set(k, String(v))
  const out = [...map.entries()].map(([k, v]) => `${k}=${v}`).join('\n') + '\n'
  writeFileSync(path, out, 'utf-8')
}

export function readServerProperties(dir: string): Record<string, string> {
  const path = join(dir, 'server.properties')
  if (!existsSync(path)) return {}
  const map: Record<string, string> = {}
  for (const line of readFileSync(path, 'utf-8').split(/\r?\n/)) {
    if (!line || line.startsWith('#')) continue
    const eq = line.indexOf('=')
    if (eq > 0) map[line.slice(0, eq)] = line.slice(eq + 1)
  }
  return map
}

function velocityToml(port: number): string {
  // Minimal but valid velocity.toml — Velocity fills in any missing defaults on first start.
  return `# Auto-generated by Birdflop Server Manager.
config-version = "2.7"
bind = "0.0.0.0:${port}"
motd = "<#54daf4>A Velocity Server"
show-max-players = 500
online-mode = true
force-key-authentication = true
prevent-client-proxy-connections = false
player-info-forwarding-mode = "NONE"
announce-forge = false
kick-existing-players = false
ping-passthrough = "DISABLED"

[servers]

[forced-hosts]

[advanced]

[query]
enabled = false
port = ${port}
`
}

function bungeeConfigYml(port: number): string {
  // BungeeCord/Waterfall default config.yml with our chosen bind + query port.
  return `# Auto-generated by Birdflop Server Manager.
listeners:
- query_port: ${port}
  motd: '&1A BungeeCord Server'
  priorities:
  - lobby
  bind_local_address: true
  host: 0.0.0.0:${port}
  max_players: 1
  tab_size: 60
  force_default_server: false
  tab_list: GLOBAL_PING
  query_enabled: false
  proxy_protocol: false
  ping_passthrough: false
servers:
  lobby:
    motd: '&1Just another BungeeCord - Forced Host'
    address: localhost:25565
    restricted: false
ip_forward: true
network_compression_threshold: 256
online_mode: true
prevent_proxy_connections: false
player_limit: -1
`
}

/**
 * Point a proxy at `port`. Called both at creation (no config yet → writes a template)
 * and when the port is later edited (rewrites just the bind line, preserving the rest).
 */
export function setProxyPort(dir: string, type: ServerType, port: number): void {
  if (type === 'velocity') {
    const path = join(dir, 'velocity.toml')
    if (existsSync(path)) {
      const updated = readFileSync(path, 'utf-8').replace(
        /^(\s*bind\s*=\s*).*$/m,
        (_m, prefix) => `${prefix}"0.0.0.0:${port}"`
      )
      writeFileSync(path, updated, 'utf-8')
    } else {
      writeFileSync(path, velocityToml(port), 'utf-8')
    }
    return
  }

  // BungeeCord + Waterfall share config.yml.
  const path = join(dir, 'config.yml')
  if (existsSync(path)) {
    const updated = readFileSync(path, 'utf-8')
      .replace(/^(\s*host:\s*).*$/m, (_m, prefix) => `${prefix}0.0.0.0:${port}`)
      .replace(/^(\s*query_port:\s*).*$/m, (_m, prefix) => `${prefix}${port}`)
    writeFileSync(path, updated, 'utf-8')
  } else {
    writeFileSync(path, bungeeConfigYml(port), 'utf-8')
  }
}
