import { join } from 'node:path'
import { writeFileSync, readFileSync, existsSync, mkdirSync } from 'node:fs'
import { randomBytes } from 'node:crypto'
import { load as yamlLoad, dump as yamlDump } from 'js-yaml'
import type { ProxyBackend, ServerType } from '@shared/types'

type Dict = Record<string, unknown>

function asDict(value: unknown): Dict {
  return value && typeof value === 'object' && !Array.isArray(value) ? (value as Dict) : {}
}

export function writeEula(dir: string, accepted: boolean): void {
  writeFileSync(join(dir, 'eula.txt'), `eula=${accepted ? 'true' : 'false'}\n`, 'utf-8')
}

/** Merge/set keys in server.properties, creating the file if it doesn't exist. */
export function setServerProperties(dir: string, kv: Record<string, string | number>): void {
  const path = join(dir, 'server.properties')
  const map = new Map<string, string>()
  if (existsSync(path)) {
    for (const line of readFileSync(path, 'utf-8').split(/\r?\n/)) {
      if (!line || line.startsWith('#')) continue
      const eq = line.indexOf('=')
      if (eq > 0) map.set(line.slice(0, eq), line.slice(eq + 1))
    }
  }
  for (const [k, v] of Object.entries(kv)) map.set(k, String(v))
  const out = [...map.entries()].map(([k, v]) => `${k}=${v}`).join('\n') + '\n'
  writeFileSync(path, out, 'utf-8')
}

export function readServerProperties(dir: string): Record<string, string> {
  const path = join(dir, 'server.properties')
  if (!existsSync(path)) return {}
  const map: Record<string, string> = {}
  for (const line of readFileSync(path, 'utf-8').split(/\r?\n/)) {
    if (!line || line.startsWith('#')) continue
    const eq = line.indexOf('=')
    if (eq > 0) map[line.slice(0, eq)] = line.slice(eq + 1)
  }
  return map
}

function velocityToml(port: number): string {
  // Minimal but valid velocity.toml — Velocity fills in any missing defaults on first start.
  return `# Auto-generated by Birdflop Server Manager.
config-version = "2.7"
bind = "0.0.0.0:${port}"
motd = "<#54daf4>A Velocity Server"
show-max-players = 500
online-mode = true
force-key-authentication = true
prevent-client-proxy-connections = false
player-info-forwarding-mode = "NONE"
announce-forge = false
kick-existing-players = false
ping-passthrough = "DISABLED"

[servers]

[forced-hosts]

[advanced]

[query]
enabled = false
port = ${port}
`
}

function bungeeConfigYml(port: number): string {
  // BungeeCord/Waterfall default config.yml with our chosen bind + query port.
  return `# Auto-generated by Birdflop Server Manager.
listeners:
- query_port: ${port}
  motd: '&1A BungeeCord Server'
  priorities:
  - lobby
  bind_local_address: true
  host: 0.0.0.0:${port}
  max_players: 1
  tab_size: 60
  force_default_server: false
  tab_list: GLOBAL_PING
  query_enabled: false
  proxy_protocol: false
  ping_passthrough: false
servers:
  lobby:
    motd: '&1Just another BungeeCord - Forced Host'
    address: localhost:25565
    restricted: false
ip_forward: true
network_compression_threshold: 256
online_mode: true
prevent_proxy_connections: false
player_limit: -1
`
}

/**
 * Point a proxy at `port`. Called both at creation (no config yet → writes a template)
 * and when the port is later edited (rewrites just the bind line, preserving the rest).
 */
export function setProxyPort(dir: string, type: ServerType, port: number): void {
  if (type === 'velocity') {
    const path = join(dir, 'velocity.toml')
    if (existsSync(path)) {
      const updated = readFileSync(path, 'utf-8').replace(
        /^(\s*bind\s*=\s*).*$/m,
        (_m, prefix) => `${prefix}"0.0.0.0:${port}"`
      )
      writeFileSync(path, updated, 'utf-8')
    } else {
      writeFileSync(path, velocityToml(port), 'utf-8')
    }
    return
  }

  // BungeeCord + Waterfall share config.yml.
  const path = join(dir, 'config.yml')
  if (existsSync(path)) {
    const updated = readFileSync(path, 'utf-8')
      .replace(/^(\s*host:\s*).*$/m, (_m, prefix) => `${prefix}0.0.0.0:${port}`)
      .replace(/^(\s*query_port:\s*).*$/m, (_m, prefix) => `${prefix}${port}`)
    writeFileSync(path, updated, 'utf-8')
  } else {
    writeFileSync(path, bungeeConfigYml(port), 'utf-8')
  }
}

/** Sanitize a backend name into a config-safe identifier (lowercase, alnum/_/-). */
export function proxyServerName(name: string): string {
  return (
    name
      .toLowerCase()
      .replace(/[^a-z0-9_-]+/g, '-')
      .replace(/^-+|-+$/g, '')
      .slice(0, 40) || 'server'
  )
}

function velocityServersBlock(backends: ProxyBackend[]): string {
  const entries = backends.map((b) => `${b.name} = "${b.address}"`).join('\n')
  const tryArr = backends.map((b) => `"${b.name}"`).join(', ')
  return `[servers]\n${entries}${entries ? '\n' : ''}try = [${tryArr}]\n`
}

function bungeeServersBlock(backends: ProxyBackend[]): string {
  if (!backends.length) return 'servers: {}\n'
  const body = backends
    .map(
      (b) =>
        `  ${b.name}:\n    motd: '&7${b.name}'\n    address: ${b.address}\n    restricted: false`
    )
    .join('\n')
  return `servers:\n${body}\n`
}

function bungeePrioritiesBlock(backends: ProxyBackend[]): string {
  if (!backends.length) return '  priorities: []\n'
  return `  priorities:\n${backends.map((b) => `  - ${b.name}`).join('\n')}\n`
}

/**
 * Rewrite just the backend-server section of a proxy's config, preserving the rest.
 * Assumes the config already exists (the caller ensures it via setProxyPort).
 */
export function writeProxyBackends(
  dir: string,
  type: ServerType,
  backends: ProxyBackend[]
): void {
  if (type === 'velocity') {
    const path = join(dir, 'velocity.toml')
    if (!existsSync(path)) return
    let content = readFileSync(path, 'utf-8')
    const block = velocityServersBlock(backends).trimEnd()
    // Replace the [servers] section up to the next top-level [section] header.
    content = /\[servers\][\s\S]*?(?=\n\[)/.test(content)
      ? content.replace(/\[servers\][\s\S]*?(?=\n\[)/, block)
      : `${content.trimEnd()}\n\n${block}\n`
    writeFileSync(path, content, 'utf-8')
    return
  }

  // BungeeCord + Waterfall (config.yml).
  const path = join(dir, 'config.yml')
  if (!existsSync(path)) return
  let content = readFileSync(path, 'utf-8')
  // Top-level `servers:` block (key line + all following indented lines).
  const serversRe = /^servers:.*\n(?:[ \t].*\n)*/m
  content = serversRe.test(content)
    ? content.replace(serversRe, bungeeServersBlock(backends))
    : `${content.trimEnd()}\n${bungeeServersBlock(backends)}`
  // `priorities:` list nested under the listener.
  const prioRe = /^[ \t]*priorities:.*\n(?:[ \t]*-.*\n)*/m
  if (prioRe.test(content)) content = content.replace(prioRe, bungeePrioritiesBlock(backends))
  writeFileSync(path, content, 'utf-8')
}

/**
 * Switch a Velocity proxy to modern player-info forwarding: ensure a shared secret file,
 * set the forwarding mode + secret-file path in velocity.toml, and return the secret so
 * backends can be wired to match. Assumes velocity.toml exists (caller ensures via setProxyPort).
 */
export function ensureVelocityForwarding(dir: string): string {
  const secretPath = join(dir, 'forwarding.secret')
  let secret = ''
  if (existsSync(secretPath)) secret = readFileSync(secretPath, 'utf-8').trim()
  if (!secret) secret = randomBytes(12).toString('hex')
  writeFileSync(secretPath, secret, 'utf-8')

  const tomlPath = join(dir, 'velocity.toml')
  let toml = existsSync(tomlPath) ? readFileSync(tomlPath, 'utf-8') : velocityToml(25577)
  toml = /^\s*player-info-forwarding-mode\s*=/m.test(toml)
    ? toml.replace(/^(\s*player-info-forwarding-mode\s*=\s*).*$/m, '$1"modern"')
    : `player-info-forwarding-mode = "modern"\n${toml}`
  if (/^\s*forwarding-secret-file\s*=/m.test(toml)) {
    toml = toml.replace(/^(\s*forwarding-secret-file\s*=\s*).*$/m, '$1"forwarding.secret"')
  } else {
    toml = toml.replace(
      /^(\s*player-info-forwarding-mode\s*=.*)$/m,
      '$1\nforwarding-secret-file = "forwarding.secret"'
    )
  }
  writeFileSync(tomlPath, toml, 'utf-8')
  return secret
}

/**
 * Wire a Paper-family backend (Paper/Folia/Purpur) for Velocity modern forwarding: enable the
 * velocity proxy section in config/paper-global.yml with the shared secret, and force the
 * server itself to offline mode (the proxy authenticates players). Paper merges any missing
 * keys on next start, so writing a partial file is safe even before the server's first run.
 */
export function enablePaperVelocity(dir: string, secret: string): void {
  const configDir = join(dir, 'config')
  mkdirSync(configDir, { recursive: true })
  const path = join(configDir, 'paper-global.yml')

  let doc: Dict = {}
  if (existsSync(path)) {
    try {
      doc = asDict(yamlLoad(readFileSync(path, 'utf-8')))
    } catch {
      doc = {}
    }
  }
  const proxies = asDict(doc.proxies)
  proxies.velocity = { ...asDict(proxies.velocity), enabled: true, 'online-mode': false, secret }
  doc.proxies = proxies
  writeFileSync(path, yamlDump(doc, { lineWidth: -1 }), 'utf-8')

  // The backend must be offline-mode so the proxy handles authentication.
  setServerProperties(dir, { 'online-mode': 'false' })
}

/** Server types that support Velocity modern forwarding natively (no extra mod). */
export function supportsModernForwarding(type: ServerType): boolean {
  return type === 'paper' || type === 'folia' || type === 'purpur'
}
